routes/web.php
<?php

use App\Http\Controllers\LoginController;
use App\Http\Controllers\PostController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
Route::get('/login',[LoginController::class, 'form'])->name('login');
Route::post('/login',[LoginController::class, 'connect'])->name('login.connect');
Route::get('/signUp', LoginController::class . '@signUp')->name('login.signUpForm'); // different way to call the controller
Route::post('/signUp',[LoginController::class, 'register'])->name('login.register');
Route::get('/logout',[LoginController::class, 'logout'])->name('logout');

Route::resource('posts',PostController::class)->except('show');

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'description',
        'user_id'
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/LoginController.php
<?php
namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Contracts\Session\Session;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class LoginController extends Controller
{
    public function form()
    {
        return view('login.signInForm');
    }
    public function connect(Request $request)
    {
        $credentials = $request->only('email','password');
        if(Auth::attempt($credentials)){
            $request->session()->regenerate();
            return to_route('welcome');
        }else{
            return back()->withErrors([
                'email' => 'Email / Password incorrect !!!'
            ])->onlyInput('email');
        }
    }
    public function signUp()
    {
        return view('login.signUpForm');
    }
    public function register(Request $request)
    {
        $validatedData = $request->validate([
            'name' => 'required|string',
            'email' => ['required','email'],
            'password' => ['required','min:8']
        ]);
        User::create($validatedData);
        return to_route('login');
    }
    public function logout(Session $session)
    {
        $session->flush();
        Auth::logout();
        return to_route('login');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use App\Models\User;
use Illuminate\Http\Request;

class PostController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    public function index()
    {
        $posts = Post::all();
        return view('posts.index',compact('posts'));
    }
    public function create()
    {
        // $users = User::all();
        return view('posts.create');
    }
    public function store(Request $request)
    {
        $user = auth()->user()->id;
        $validatedData = $request->validate([
            'title' => 'required|max:25',
            'description' => 'required'
        ]);
        $validatedData['user_id'] = $user;
        Post::create($validatedData);
        return to_route('posts.index')->with('success','La publication a été ajoutée avec success ✔');
    }
    public function edit($id)
    {
        $post = Post::findOrFail($id);
        return view('posts.edit',compact('post'));
    }
    public function update($id, Request $request)
    {
        $post = Post::findOrFail($id);
        $validatedData = $request->validate([
            'title' => 'required|max:25',
            'description' => 'required'
        ]);
        $post->update($validatedData);
        return to_route('posts.index')->with('success','La publication a été modifiée avec success ✔');
    }
    public function destroy($id)
    {
        $post = Post::find($id);
        $post->delete();
        return to_route('posts.index')->with('success','La publication a été supprimée avec success ✔');
    }
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>AUTH</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <style>
        body {
            background-color: #08AEEA;
        }
    </style>

</head>

<body>

    <nav class="navbar navbar-expand-lg ">
        <div class="container-fluid ">
            <div class="collapse navbar-collapse d-flex mb-3">
                <h4><a class="nav-link  p-2" href="{{route('welcome')}}">My App</a></h4>
                <a class="nav-link ms-5" href="{{route('posts.index')}}">Posts</a>
                @auth
                <div class="ms-3 navbar-nav ms-auto p-2 ">
                    <a class="nav-link active" href="#">{{auth()->user()->name}}</a>
                    <a class="nav-link badge rounded-pill text-bg-danger fs-6 p-3" href="{{route('logout')}}">Log out</a>
                </div>
                @endauth
                @guest
                <div class="ms-3 navbar-nav ms-auto p-2">
                    <a class="nav-link badge rounded-pill text-bg-primary fs-6 p-3" href="{{route('login')}}">Log in</a>
                </div>
                @endguest
            </div>
        </div>
    </nav>

    <div class="container mt-3 ">
        @yield('content')
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>

</html>

resources/views/login/signInForm.blade.php
@extends('layouts.app')
@section('content')

<div class="h-100">
    <div class="row d-flex align-items-center justify-content-center h-100">
        <div class="col-md-7 col-lg-5 col-xl-5 offset-xl-1">
            <form action="{{route('login.connect')}}" method="post">
                @csrf

                <div class="mb-3">
                    <label for="email" class="form-label">Email</label>
                    <input type="email" class="form-control" name="email" value="{{old('email')}}" />
                    @error('email')
                    <span class="text text-danger">{{$message}}</span>
                    @enderror
                </div>

                <div class="form-outline mb-4">
                    <label class="form-label" for="form1Example23">Password</label>
                    <input type="password" name="password" class="form-control form-control-lg" />
                </div>
                <div class="d-flex justify-content-around align-items-center mb-4">
                <button type="submit" class="btn btn-primary btn-lg btn-block">Sign in</button>
                <a href="{{route('login.signUpForm')}}" class="btn btn-secondary btn-lg btn-block">Create account</a>
            </form>
        </div>
    </div>
</div>

@endsection

resources/views/login/signUpForm.blade.php
@extends('layouts.app')
@section('content')

<div class="h-100">
    <div class="row d-flex align-items-center justify-content-center h-100">
        <div class="col-md-7 col-lg-5 col-xl-5 offset-xl-1">
            <form action="{{route('login.register')}}" method="post">
                @csrf

                
                    <div class="mb-3">
                        <label for="name" class="form-label">Name</label>
                        <input type="text" class="form-control" name="name" value="{{old('name')}}" />
                        @error('name')
                        <span class="text text-danger">{{$message}}</span>
                        @enderror
                    </div>
                    <div class="mb-3">
                        <label for="email" class="form-label">Email</label>
                        <input type="text" class="form-control" name="email" value="{{old('email')}}" />
                        @error('email')
                        <span class="text text-danger">{{$message}}</span>
                        @enderror
                    </div>
                    <div class="mb-3">
                        <label for="password" class="form-label">Password</label>
                        <input type="password" class="form-control" name="password" />
                        @error('password')
                        <span class="text text-danger">{{$message}}</span>
                        @enderror
                    </div>
                <div class="d-flex justify-content-around align-items-center mb-4">
                    <input type="submit" class="btn btn-dark btn-lg" value="Register">
                    <a href="{{route('login')}}">Already have an account?</a>
                </div>
            </form>
        </div>
    </div>

</div>

@endsection

resources/views/posts/create.blade.php
@extends('layouts.app')
@section('content')

<form action="{{route('posts.store')}}" method="post">
    @csrf
    <div class="mb-3">
        <label class="form-label">Titre</label>
        <input type="text" class="form-control" name="title" placeholder="title" value="{{old('title')}}" />
    </div>
    <div class="mb-3">
        <label class="form-label">Description</label>
        <textarea class="form-control" name="description" placeholder="description">{{old('description')}}</textarea>
    </div>
    <input type="submit" value="Ajouter" class="btn btn-light">
    <a href="{{url()->previous()}}" class="btn btn-secondary">Back</a>
    
</form>

@endsection

resources/views/posts/edit.blade.php
@extends('layouts.app')
@section('content')

<form action="{{route('posts.update',$post)}}" method="post">
    @csrf
    @method('put')
    <div class="mb-3">
        <label class="form-label">Titre</label>
        <input type="text" class="form-control" name="title" placeholder="title" value="{{old('title',$post->title)}}" />
    </div>
    <div class="mb-3">
        <label class="form-label">Description</label>
        <textarea class="form-control" name="description" placeholder="description">{{old('description',$post->description)}}</textarea>
    </div>
    <input type="submit" value="Modifier" class="btn btn-light">
    <a href="{{url()->previous()}}" class="btn btn-secondary">Back</a>

</form>

@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')
@section('content')

@if(session('success'))
<div class="alert alert-success">
    {{session('success')}}
</div>
@endif

<a href="{{route('posts.create')}}" class="btn btn-dark">Ajouter une publication</a>
<table class="table table-dark my-3">
    <thead>
        <th>#</th>
        <th>Titre</th>
        <th>Description</th>
        <th>Publier par</th>
        <th>Date de dernier mise à jour</th>
        <th>Actions</th>
    </thead>
    <tbody>
        @foreach($posts as $index => $p)
        <tr>
            <td>{{$index+1}}</td>
            <td>{{$p->title}}</td>
            <td>{{$p->description}}</td>
            <td>{{$p->user->name}}</td>
            <td>{{$p->updated_at}}</td>
            <td>
                <a href="{{route('posts.edit',$p->id)}}" class="btn btn-warning">Modifier</a>
                <form method="post" action="{{route('posts.destroy',$p->id)}}" style="display: inline">
                    @csrf
                    @method('delete')
                    <button type="submit" class="btn btn-danger">Supprimer</button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
</table>

@endsection